app:
  app_name: "transaction-service"
  app_version: "1.0.0"
  app_environment: "development"
  app_base_dir: ""
  app_time_zone: "Asia/Jakarta"

httpserver:
  httpserver_port: "8080"
  httpserver_use_ssl: false
  httpserver_ssl_key: ""
  httpserver_ssl_cert: ""

httpclient:
  httpc_max_idle_conns: 100
  httpc_max_idle_conns_per_host: 100
  httpc_insecure_skip_verify: true
  httpc_set_timeout: 30
  httpc_use_client_ssl: false

logger:
  log_level: "debug"
  log_path: "."

mysql:
  mysql_driver_name: "mysql"
  mysql_max_open_conns: 100
  mysql_max_idle_conns: 100
  mysql_max_lifetime_conns: 5
  mysql_lifetime_conns_unit: ""
  mysql_url: "root:password@tcp(127.0.0.1:3306)/multifinance?charset=utf8mb4&parseTime=True&loc=Local"
